# Generated by Django 5.0.6 on 2024-12-21 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(null=True, upload_to='')),
                ('a1', models.CharField(max_length=250, null=True)),
                ('a2', models.CharField(max_length=250, null=True)),
                ('a3', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fromyear', models.SmallIntegerField(null=True)),
                ('geojson_data', models.JSONField(default=list)),
                ('storytext', models.CharField(max_length=350)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('verification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.verification')),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.AddConstraint(
            model_name='markers',
            constraint=models.UniqueConstraint(fields=('fromyear', 'storytext'), name='unique_story'),
        ),
    ]
