# Generated by Django 5.0.6 on 2024-09-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fromyear', models.SmallIntegerField(null=True)),
                ('storytext', models.CharField(max_length=350)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
    ]
