# Generated by Django 5.0.6 on 2024-09-23 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markers',
            old_name='langitude',
            new_name='latitude',
        ),
    ]
