# Generated by Django 5.0.6 on 2025-02-08 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markers',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='markers',
            name='storytext',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='markers',
            name='verification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.verification'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='a1',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='a2',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='a3',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
