# Generated by Django 5.0.6 on 2024-11-13 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_langitude_markers_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='markers',
            name='geojson_data',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(null=True, upload_to='')),
                ('a1', models.CharField(max_length=250, null=True)),
                ('a2', models.CharField(max_length=250, null=True)),
                ('a3', models.CharField(max_length=250, null=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.markers')),
            ],
        ),
    ]
